version: '3.7'

services:
    db:
        image: postgres
        restart: always
        env_file:
            - webnmap.env
    queue:
        image: 'rabbitmq:3'
        env_file:
            - webnmap.env
    worker:
        build: .
        env_file:
            - webnmap.env
        command: bash -c "apt-get update && apt-get install -y nmap && cd /opt/webnmap && celery -A webnmap worker -l info"
        depends_on: 
            - db
            - queue
    web:
        build: .
        env_file:
            - webnmap.env
        command: bash -c "cd /opt/webnmap && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db
            - queue
            - worker
        ports:
            - "0.0.0.0:8000:8000"